# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Carlos Perez Araujo/Proyectos Personales/Vhdl/Xilinx/LCDScrolll/project_3/project_3.cache/wt} [current_project]
set_property parent.project_path {C:/Carlos Perez Araujo/Proyectos Personales/Vhdl/Xilinx/LCDScrolll/project_3/project_3.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {{C:/Carlos Perez Araujo/Proyectos Personales/Vhdl/Xilinx/LCDScrolll/LCD_SCROLL.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top LCD -part xc7k70tfbv676-1


write_checkpoint -force -noxdef LCD.dcp

catch { report_utilization -file LCD_utilization_synth.rpt -pb LCD_utilization_synth.pb }
