LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY CLK100HZ IS
	PORT (
		MCLK : IN STD_LOGIC;
		CLKOUT : OUT STD_LOGIC
	);
END CLK100HZ;

ARCHITECTURE Behavioral OF CLK100HZ IS
	SIGNAL COUNTER : STD_LOGIC_VECTOR(18 DOWNTO 0);
	SIGNAL C100HZ : STD_LOGIC;
BEGIN
	PROCESS (MCLK)
	BEGIN
		IF MCLK = '1' AND MCLK'EVENT THEN
			IF COUNTER = 250000 THEN
				COUNTER <= (OTHERS => '0');
				C100HZ <= NOT C100HZ;
			ELSE COUNTER <= COUNTER + 1;
			END IF;
		ELSE NULL;
		END IF;
	END PROCESS;

	CLKOUT <= C100HZ;
END Behavioral;